In [1]:
import torch

## One dimensional case

**Definimos un vector compatible con pytorch**

In [2]:
x = torch.tensor([1., 2.], requires_grad = True).view(-1,1)
print('x: ',x)
print('Obs: con \'requires_grad=True\' indicamos que queremos calcular derivadas parciales c/r a esta variable')

x:  tensor([[1.],
        [2.]], grad_fn=<ViewBackward0>)
Obs: con 'requires_grad=True' indicamos que queremos calcular derivadas parciales c/r a esta variable


**Definimos una función no lineal**

$$f(x) = 2x^3 + 5x^2 + 8$$

In [3]:
y = 2*x**3 + 5*x**2 + 8

**Calculamos su primera derivada**

$$\frac{\partial f (x)}{\partial x}\Bigr\rvert_{x = [1,2]} = 6x^2 + 10x \Bigr\rvert_{x = [1,2]}$$

In [4]:
# dy/dx = 6*x**2 + 10*x
first_derivative = torch.autograd.grad(y, x, 
                                       grad_outputs=torch.ones_like(y), 
                                       create_graph=True)[0]
print(first_derivative)

tensor([[16.],
        [44.]], grad_fn=<AddBackward0>)


**Calculamos su segunda derivada**

$$\frac{\partial^2 f (x)}{\partial x^2}\Bigr\rvert_{x = [1,2]} = 12x + 10 \Bigr\rvert_{x = [1,2]}$$

In [5]:
# d(dy/dx)/dx = 12*x + 10
second_derivative = torch.autograd.grad(first_derivative, x,  
                                        grad_outputs=torch.ones_like(y))[0]
print(second_derivative)

tensor([[22.],
        [34.]])


## Two dimensional case

In [6]:
x = torch.tensor([1., 2.], requires_grad = True).view(-1,1)
t = torch.tensor([.1, .2], requires_grad = True).view(-1,1)

In [7]:
u = 2*x**2 + 5*x*t + t**2 + 5.

In [8]:
# dy/dx = 4*x + 5*t
first_derivative = torch.autograd.grad(u, x, 
                                       grad_outputs=torch.ones_like(y), 
                                       create_graph=True)[0]
print(first_derivative)

tensor([[4.5000],
        [9.0000]], grad_fn=<AddBackward0>)


In [9]:
# d(dy/dx)/dx = 4
second_derivative = torch.autograd.grad(first_derivative, x,  
                                        grad_outputs=torch.ones_like(y))[0]
print(second_derivative)

tensor([[4.],
        [4.]])
